<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="Schunk_Vacuum_Tools" params="launch_mode">
  
    <!-- Loading of the Robot Joint calibrations and bringup config -->
          <xacro:if value="${launch_mode == 'sim_HW'}">
              <xacro:property name="pm_robot_joint_calibraion_file" value="$(find pm_robot_description)/calibration_config/pm_robot_joint_calibration.yaml" />
              <xacro:property name="pm_robot_bringup_config_file" value="$(find pm_robot_bringup)/config/pm_robot_bringup_config.yaml" />
          </xacro:if>


    <!-- Loading of the Robot Joint calibrations and bringup config -->
    <!-- If launch_mode 'real' a local path can be specified for the calibration file -->
          <xacro:if value="${launch_mode == 'real_HW'}">
              <xacro:property name="local_file_paths__file" value="$(find pm_robot_description)/calibration_config/pm_robot_path_real_HW.yaml" />
              <xacro:property name="path_dict" value="${xacro.load_yaml(local_file_paths__file)}"/>
          
              <xacro:property name="local_calibration_file_path" value="${path_dict['pm_robot_calibration_file_path']}"/>
              <xacro:property name="local_robot_bringup_file_path" value="${path_dict['pm_robot_bringup_config_file_path']}"/>
          
              <!-- REAL -->
              <!-- <xacro:property name="pm_robot_joint_calibraion_file" value="${local_calibration_file_path}" />
              <xacro:property name="pm_robot_bringup_config_file" value="${local_robot_bringup_file_path}"/> -->
          
              <!-- SIM -->
              <xacro:property name="pm_robot_joint_calibraion_file" value="$(find pm_robot_description)/calibration_config/pm_robot_joint_calibration.yaml" />
              <xacro:property name="pm_robot_bringup_config_file" value="$(find pm_robot_bringup)/config/pm_robot_bringup_config.yaml" />
        
          </xacro:if>
  
    <xacro:property name="current_pm_robot_bringup_config" value="${xacro.load_yaml(pm_robot_bringup_config_file)}"/>
    <xacro:property name="current_vacuum_tool" value="${current_pm_robot_bringup_config['pm_robot_tools']['pm_robot_vacuum_tools']['use_tool']}"/>
    <xacro:property name="current_vacuum_tool_tip" value="${current_pm_robot_bringup_config['pm_robot_tools']['pm_robot_vacuum_tools']['use_tip']}"/>

    <xacro:property name="calibration_dict" value="${xacro.load_yaml(pm_robot_joint_calibraion_file)}"/>

    <!-- Init Definition of vacuum tool dict -->
    <xacro:property name="vacuum_tools_configs_file" value="$(find pm_robot_description)/urdf/urdf_configs/schunk_vacuum_tools.yaml" />
    <xacro:property name="vacuum_tool_configs_dict" value="${xacro.load_yaml(vacuum_tools_configs_file)}"/>

    <xacro:property name="vacuum_tool_holder_configs_dict" value="${vacuum_tool_configs_dict[current_vacuum_tool]}"/>
    <xacro:property name="vacuum_tool_tip_configs_dict" value="${vacuum_tool_configs_dict[current_vacuum_tool][current_vacuum_tool_tip]}"/>

    <!-- Config for the vacuum tool holder -->
    <xacro:property name="vacuum_tool_xyz" value="${vacuum_tool_holder_configs_dict['xyz']}"/>
    <xacro:property name="vacuum_tool_rpy" value="${vacuum_tool_holder_configs_dict['rpy']}"/>
    <xacro:property name="vacuum_tool_mass" value="${vacuum_tool_holder_configs_dict['mass']}"/>
    <xacro:property name="vacuum_tool_inertia_ixx" value="${vacuum_tool_holder_configs_dict['inertia_ixx']}"/>
    <xacro:property name="vacuum_tool_inertia_ixy" value="${vacuum_tool_holder_configs_dict['inertia_ixy']}"/>
    <xacro:property name="vacuum_tool_inertia_ixz" value="${vacuum_tool_holder_configs_dict['inertia_ixz']}"/>
    <xacro:property name="vacuum_tool_inertia_iyy" value="${vacuum_tool_holder_configs_dict['inertia_iyy']}"/>
    <xacro:property name="vacuum_tool_inertia_iyz" value="${vacuum_tool_holder_configs_dict['inertia_iyz']}"/>
    <xacro:property name="vacuum_tool_inertia_izz" value="${vacuum_tool_holder_configs_dict['inertia_izz']}"/>
    <xacro:property name="vacuum_tool_color" value="${vacuum_tool_holder_configs_dict['color']}"/>    
    <xacro:property name="vacuum_tool_visual_filename" value="${vacuum_tool_holder_configs_dict['visual_filename']}"/>
    <xacro:property name="vacuum_tool_collision_filename" value="${vacuum_tool_holder_configs_dict['collision_filename']}"/>
  
    <!-- Config for the vacuum tool tip -->
    <xacro:property name="vacuum_tip_xyz" value="${vacuum_tool_tip_configs_dict['inertia_xyz']}"/>
    <xacro:property name="vacuum_tip_rpy" value="${vacuum_tool_tip_configs_dict['inertia_rpy']}"/>
    <xacro:property name="vacuum_tip_mass" value="${vacuum_tool_tip_configs_dict['mass']}"/>
    <xacro:property name="vacuum_tip_inertia_ixx" value="${vacuum_tool_tip_configs_dict['inertia_ixx']}"/>
    <xacro:property name="vacuum_tip_inertia_ixy" value="${vacuum_tool_tip_configs_dict['inertia_ixy']}"/>
    <xacro:property name="vacuum_tip_inertia_ixz" value="${vacuum_tool_tip_configs_dict['inertia_ixz']}"/>
    <xacro:property name="vacuum_tip_inertia_iyy" value="${vacuum_tool_tip_configs_dict['inertia_iyy']}"/>
    <xacro:property name="vacuum_tip_inertia_iyz" value="${vacuum_tool_tip_configs_dict['inertia_iyz']}"/>
    <xacro:property name="vacuum_tip_inertia_izz" value="${vacuum_tool_tip_configs_dict['inertia_izz']}"/>
    <xacro:property name="vacuum_tip_color" value="${vacuum_tool_tip_configs_dict['color']}"/>    
    <xacro:property name="vacuum_tip_visual_filename" value="${vacuum_tool_tip_configs_dict['visual_filename']}"/>
    <xacro:property name="vacuum_tip_collision_filename" value="${vacuum_tool_tip_configs_dict['collision_filename']}"/>

    <xacro:property name="pm_robot_tool_TCP_z_offset" value="${vacuum_tool_holder_configs_dict['tool_TCP_z_offset']}"/>
    <xacro:property name="pm_robot_tool_TCP_y_offset" value="${vacuum_tool_holder_configs_dict['tool_TCP_y_offset']}"/>
    <xacro:property name="pm_robot_tool_TCP_x_offset" value="${vacuum_tool_holder_configs_dict['tool_TCP_x_offset']}"/>

  <link name="PM_Robot_Tool_TCP">
  </link>
  
  <xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_x" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['x_offset']}"/>
  <xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_y" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['y_offset']}"/>
  <xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_z" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['z_offset']}"/>
  <xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_rx" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['rx_offset']}"/>
  <xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_ry" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['ry_offset']}"/>
  <xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_rz" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['rz_offset']}"/>

  <joint name="PM_Robot_Tool_TCP_Joint" type="fixed">
    <origin xyz="
      ${0 + pm_robot_tool_TCP_x_offset + PM_Robot_Tool_TCP_Joint_Cal_x * 0.000001} 
      ${0 + pm_robot_tool_TCP_y_offset + PM_Robot_Tool_TCP_Joint_Cal_y * 0.000001} 
      ${0 - 0.04542 - pm_robot_tool_TCP_z_offset + PM_Robot_Tool_TCP_Joint_Cal_z * 0.000001}" rpy="
      ${0 + PM_Robot_Tool_TCP_Joint_Cal_rx * 3.14159265359/180} 
      ${0 + PM_Robot_Tool_TCP_Joint_Cal_ry * 3.14159265359/180} 
      ${0 + PM_Robot_Tool_TCP_Joint_Cal_rz * 3.14159265359/180}" />
    <parent link="Gripper_Rot_Plate" />
    <child link="PM_Robot_Tool_TCP" />
    <axis xyz="0 0 0" />
  </joint>

  <link
    name="PM_Robot_Vacuum_Tool">
    <inertial>
      <origin
        xyz="${vacuum_tool_xyz}"
        rpy="${vacuum_tool_rpy}"/>
      <mass
        value="${vacuum_tool_mass}"/>
      <inertia
        ixx="${vacuum_tool_inertia_ixx}"
        ixy="${vacuum_tool_inertia_ixy}"
        ixz="${vacuum_tool_inertia_ixz}"
        iyy="${vacuum_tool_inertia_iyy}"
        iyz="${vacuum_tool_inertia_iyz}"
        izz="${vacuum_tool_inertia_izz}" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Schunk_Vacuum_Tools/${vacuum_tool_visual_filename}" />      
      </geometry>
      <material
        name="${vacuum_tool_color}">
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Schunk_Vacuum_Tools/${vacuum_tool_collision_filename}" />         
      </geometry>
    </collision>
  </link>

    <!---Gravity off-->
    <gazebo reference="PM_Robot_Vacuum_Tool">
        <turnGravityOff>true</turnGravityOff>
        <color>1.0 0 0.5 1.0</color>
    </gazebo>
  
  <joint
    name="PM_Robot_Vacuum_Tool_Joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent
      link="PM_Robot_Tool_TCP" />
    <child
      link="PM_Robot_Vacuum_Tool" />
    <axis
      xyz="0 0 0" />
  </joint>

  <link
    name="PM_Robot_Vacuum_Tool_Tip">
    <inertial>
      <origin
        xyz="${vacuum_tip_xyz}"
        rpy="${vacuum_tip_rpy}"/>
      <mass
        value="${vacuum_tip_mass}"/>
      <inertia
        ixx="${vacuum_tip_inertia_ixx}"
        ixy="${vacuum_tip_inertia_ixy}"
        ixz="${vacuum_tip_inertia_ixz}"
        iyy="${vacuum_tip_inertia_iyy}"
        iyz="${vacuum_tip_inertia_iyz}"
        izz="${vacuum_tip_inertia_izz}" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Schunk_Vacuum_Tools/${vacuum_tip_visual_filename}" />      
      </geometry>
      <material
        name="${vacuum_tip_color}">
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Schunk_Vacuum_Tools/${vacuum_tip_collision_filename}" />         
      </geometry>
    </collision>
  </link>

    <!---Gravity off-->
    <gazebo reference="PM_Robot_Vacuum_Tool_Tip">
        <turnGravityOff>true</turnGravityOff>
        <color>1.0 0 0.5 1.0</color>
    </gazebo>
  
  <joint
    name="PM_Robot_Vacuum_Tool_Tip_Joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent
      link="PM_Robot_Tool_TCP" />
    <child
      link="PM_Robot_Vacuum_Tool_Tip" />
    <axis
      xyz="0 0 0" />
  </joint>

</xacro:macro>

</robot>
