# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  # 1K_Dispenser_Flap_Joint:
  #   has_velocity_limits: true
  #   max_velocity: 0.050000000000000003
  #   has_acceleration_limits: false
  #   max_acceleration: 0
  # 1K_Dispenser_Joint:
  #   has_velocity_limits: true
  #   max_velocity: 0.050000000000000003
  #   has_acceleration_limits: false
  #   max_acceleration: 0
  # 2K_Dispenser_Joint:
  #   has_velocity_limits: true
  #   max_velocity: 0.050000000000000003
  #   has_acceleration_limits: false
  #   max_acceleration: 0
  # Camera_Calibartion_Joint:
  #   has_velocity_limits: true
  #   max_velocity: 0.050000000000000003
  #   has_acceleration_limits: false
  #   max_acceleration: 0
  Gonio_Right_Stage_1_Top_Joint:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  Gonio_Right_Stage_2_Bottom_Joint:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  Gripper_Rot_Plate_Joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  X_Axis_Joint:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0
  Y_Axis_Joint:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0
  Z_Axis_Joint:
    has_velocity_limits: true
    max_velocity: 0.050000000000000003
    has_acceleration_limits: false
    max_acceleration: 0