# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - testgroup_controller

  testgroup_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      #- Gonio_Right_Stage_1_Top_Joint
      #- Gonio_Right_Stage_2_Bottom_Joint
      #- Gonio_Left_Stage_1_Top_Joint
      #- Gonio_Left_Stage_2_Bottom_Joint
      - X_Axis_Joint
      - Y_Axis_Joint
      - Z_Axis_Joint
      - T_Axis_Joint
    action_ns: follow_joint_trajectory
<<<<<<< HEAD
    default: true
=======
    default: true

  pm_robot_gonio_left_JTC:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Gonio_Left_Stage_1_Joint
      - Gonio_Left_Stage_2_Joint
    action_ns: follow_joint_trajectory
    default: true
    
  pm_robot_gonio_right_JTC:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Gonio_Right_Stage_1_Joint
      - Gonio_Right_Stage_2_Joint
    action_ns: follow_joint_trajectory
    default: true


  pm_robot_parallel_gripper_GAC:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - pm_robot_Tool_Parallel_Joint
>>>>>>> f5d9834 (modular Launch Files, Axis renaming)
