# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - pm_robot_t_axis_JTC
    - pm_robot_xyz_axis_JTC

  pm_robot_t_axis_JTC:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - T_Axis_Joint
    action_ns: follow_joint_trajectory
    default: true

  pm_robot_xyz_axis_JTC:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - X_Axis_Joint
      - Y_Axis_Joint
      - Z_Axis_Joint
    action_ns: follow_joint_trajectory
    default: true