# MoveIt uses this configuration for controller management

# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 10.0
  allowed_execution_monitoring: false
  allowed_goal_duration_margin: 0.0000001
  # allowed_start_tolerance: 0.01
  # trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - pm_robot_xyz_axis_controller
    - pm_robot_t_axis_controller
    - pm_robot_parallel_gripper_GAC
    - pm_robot_gonio_right_controller
    - pm_robot_gonio_left_controller

  pm_robot_t_axis_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - T_Axis_Joint


  pm_robot_xyz_axis_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - X_Axis_Joint
      - Y_Axis_Joint
      - Z_Axis_Joint

  pm_robot_gonio_left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Gonio_Left_Stage_1_Joint
      - Gonio_Left_Stage_2_Joint
    
  pm_robot_gonio_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Gonio_Right_Stage_1_Joint
      - Gonio_Right_Stage_2_Joint

  pm_robot_parallel_gripper_GAC:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - pm_robot_Tool_Parallel_Joint
