<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="Tool_Parallel_Gripper_1_Jaw" params="launch_mode">
  
    <xacro:if value="${launch_mode == 'sim_HW'}">
        <xacro:property name="pm_robot_joint_calibraion_file" value="$(find pm_robot_description)/calibration_config/pm_robot_joint_calibration.yaml" />
        <xacro:property name="pm_robot_bringup_config_file" value="$(find pm_robot_bringup)/config/pm_robot_bringup_config.yaml" />
    </xacro:if>

    <!-- Loading of the Robot Joint calibrations and bringup config -->
    <!-- If launch_mode 'real' a local path can be specified for the calibration file -->
    <!-- If launch_mode 'real' a local path can be specified for the calibration file -->
    <xacro:if value="${launch_mode == 'real_HW'}">
      <xacro:property name="local_file_paths__file" value="$(find pm_robot_description)/calibration_config/pm_robot_path_real_HW.yaml" />
      <xacro:property name="path_dict" value="${xacro.load_yaml(local_file_paths__file)}"/>

      <xacro:property name="local_calibration_file_path" value="${path_dict['pm_robot_calibration_file_path']}"/>
      <xacro:property name="local_robot_bringup_file_path" value="${path_dict['pm_robot_bringup_config_file_path']}"/>

      <!-- REAL -->
      <xacro:property name="pm_robot_joint_calibraion_file" value="${local_calibration_file_path}" />
      <xacro:property name="pm_robot_bringup_config_file" value="${local_robot_bringup_file_path}"/>
      
      <!-- SIM -->
      <!-- <xacro:property name="pm_robot_joint_calibraion_file" value="$(find pm_robot_description)/calibration_config/pm_robot_joint_calibration.yaml" />
      <xacro:property name="pm_robot_bringup_config_file" value="$(find pm_robot_bringup)/config/pm_robot_bringup_config.yaml" /> -->

    </xacro:if>
  
    <xacro:property name="current_pm_robot_bringup_config" value="${xacro.load_yaml(pm_robot_bringup_config_file)}"/>
    <!-- <xacro:property name="current_vacuum_tool" value="${current_pm_robot_bringup_config['pm_robot_tools']['pm_robot_vacuum_tools']['use_tool']}"/>
    <xacro:property name="current_vacuum_tool_tip" value="${current_pm_robot_bringup_config['pm_robot_tools']['pm_robot_vacuum_tools']['use_tip']}"/> -->

    <xacro:property name="current_tool" value="${current_pm_robot_bringup_config['pm_robot_tools']['pm_robot_tool_parallel_gripper_1_jaw']['use_tool']}"/>
    <xacro:property name="current_jaw_attachement" value="${current_pm_robot_bringup_config['pm_robot_tools']['pm_robot_tool_parallel_gripper_1_jaw']['use_jaw_type']}"/>
    
    <xacro:property name="parallel_gripper_1_jaw_file" value="$(find pm_robot_description)/urdf/urdf_configs/parallel_gripper_1_jaw.yaml" />
    <xacro:property name="parallel_gripper_configs" value="${xacro.load_yaml(parallel_gripper_1_jaw_file)}"/>
    <xacro:property name="Gripper_jaw_1_dict" value="${parallel_gripper_configs[current_tool][current_jaw_attachement]}"/>

    <xacro:property name="calibration_dict" value="${xacro.load_yaml(pm_robot_joint_calibraion_file)}"/>

    <xacro:property name="joint_offset_value" value="${Gripper_jaw_1_dict['joint_offset_value']}"/>

    
    <link
    name="Tool_Parallel_Gripper_Body">
    <inertial>
      <origin
        xyz="-0.00355668393665556 -0.000432533962047624 -0.011659024185547"
        rpy="0 0 0" />
      <mass
        value="0.0122161706567272" />
      <inertia
        ixx="1.27374788059174E-06"
        ixy="-3.39601385359254E-05"
        ixz="2.0953297469927E-05"
        iyy="8.64679886349924E-05"
        iyz="1.56462306590584E-05"
        izz="1.76556119124177E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/SmarAct_Gripper_Base.STL" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/SmarAct_Gripper_Base.STL" />
      </geometry>
    </collision>
  </link>

  <!---Gravity off-->
  <gazebo reference="Tool_Parallel_Gripper_Body">
    <turnGravityOff>true</turnGravityOff>
    <color>1.0 0 0.5 1.0</color> 
  </gazebo>

  <joint name="Tool_Parallel_Gripper_Body_Joint" type="fixed">
    <origin xyz="0 0 -0.04542" rpy="0 0 0" />
    <parent link="t_axis_toolchanger" />
    <child link="Tool_Parallel_Gripper_Body" />
    <axis xyz="0 0 0" />
  </joint>

  <!--%%%%%%%%%%%%% Jaw 1 Parallel Gripper Definitions %%%%%%%%%%%%%-->

      <link
      name="Tool_Parallel_Gripper_Jaw">
      <inertial>
        <origin
        xyz="-0.000378376833032915 0.00363289819353893 -0.00384521007176003"
        rpy="0 0 0" />
        <mass
          value="0.000125699746806344" />
        <inertia
        ixx="1.46877530343563E-09"
        ixy="-1.08017427297462E-10"
        ixz="-1.55511351102192E-10"
        iyy="9.10321731673149E-10"
        iyz="-3.94221523852005E-10"
        izz="8.29097865963572E-10" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/SmarAct_Gripper_Jaw.STL" />
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/SmarAct_Gripper_Jaw.STL" />
        </geometry>
      </collision>
    </link>

    <!---Gravity off-->
    <gazebo reference="Tool_Parallel_Gripper_Jaw">
      <turnGravityOff>true</turnGravityOff>
    </gazebo>
    <joint
      name="Tool_Parallel_Gripper_Jaw_Joint"
      type="prismatic">
      <origin
        xyz="${-0.0025+joint_offset_value*0.001} 0.00100000018813534 -0.0520000000000005"
        rpy="0 0 0" />
      <parent
        link="Tool_Parallel_Gripper_Body" />
      <child
        link="Tool_Parallel_Gripper_Jaw" />
      <axis
        xyz="1 0 0" />
      <limit
        lower="0"
        upper="0.001"
        effort="20"
        velocity="0.05" />
    </joint>



    <link
      name="Tool_Parallel_Gripper_Jaw_1_Point">
    </link>

    <joint
      name="Tool_Parallel_Gripper_Jaw_1_Point_Joint"
      type="fixed">
      <origin
        xyz="0.00250 0.001 -0.052"
        rpy="0 0 0" />
      <parent
        link="Tool_Parallel_Gripper_Body" />
      <child
        link="Tool_Parallel_Gripper_Jaw_1_Point" />
      <axis
        xyz="0 0 0" />
    </joint>



    <link
      name="Tool_Parallel_Gripper_Jaw_2_Point">
    </link>

    <joint
      name="Tool_Parallel_Gripper_Jaw_2_Point_Joint"
      type="fixed">
      <origin
      xyz="0.0 0 0.0"
      rpy="0 0 0" />
      <parent
        link="Tool_Parallel_Gripper_Jaw" />
      <child
        link="Tool_Parallel_Gripper_Jaw_2_Point" />
      <axis
        xyz="0 0 0" />
    </joint>



  

  <!--%%%%%%%%%%%%% Jaw Definitions %%%%%%%%%%%%%-->


  <xacro:property name="Gripper_jaw_1_xyz" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_xyz']}"/>
  <xacro:property name="Gripper_jaw_1_rpy" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_rpy']}"/>
  <xacro:property name="Gripper_jaw_1_mass" value="${Gripper_jaw_1_dict['Jaw_1']['mass']}"/>
  <xacro:property name="Gripper_jaw_1_inertia_ixx" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_ixx']}"/>
  <xacro:property name="Gripper_jaw_1_inertia_ixy" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_ixy']}"/>
  <xacro:property name="Gripper_jaw_1_inertia_ixz" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_ixz']}"/>
  <xacro:property name="Gripper_jaw_1_inertia_iyy" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_iyy']}"/>
  <xacro:property name="Gripper_jaw_1_inertia_iyz" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_iyz']}"/>
  <xacro:property name="Gripper_jaw_1_inertia_izz" value="${Gripper_jaw_1_dict['Jaw_1']['inertia_izz']}"/>
  <xacro:property name="Gripper_jaw_1_visual_filename" value="${Gripper_jaw_1_dict['Jaw_1']['visual_filename']}"/>
  <xacro:property name="Gripper_jaw_1_collision_filename" value="${Gripper_jaw_1_dict['Jaw_1']['collision_filename']}"/>

  <xacro:property name="Gripper_jaw_2_xyz" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_xyz']}"/>
  <xacro:property name="Gripper_jaw_2_rpy" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_rpy']}"/>
  <xacro:property name="Gripper_jaw_2_mass" value="${Gripper_jaw_1_dict['Jaw_2']['mass']}"/>
  <xacro:property name="Gripper_jaw_2_inertia_ixx" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_ixx']}"/>
  <xacro:property name="Gripper_jaw_2_inertia_ixy" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_ixy']}"/>
  <xacro:property name="Gripper_jaw_2_inertia_ixz" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_ixz']}"/>
  <xacro:property name="Gripper_jaw_2_inertia_iyy" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_iyy']}"/>
  <xacro:property name="Gripper_jaw_2_inertia_iyz" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_iyz']}"/>
  <xacro:property name="Gripper_jaw_2_inertia_izz" value="${Gripper_jaw_1_dict['Jaw_2']['inertia_izz']}"/>
  <xacro:property name="Gripper_jaw_2_visual_filename" value="${Gripper_jaw_1_dict['Jaw_2']['visual_filename']}"/>
  <xacro:property name="Gripper_jaw_2_collision_filename" value="${Gripper_jaw_1_dict['Jaw_2']['collision_filename']}"/>


  <xacro:property name="tool_tcp_offset_x" value="${Gripper_jaw_1_dict['tool_TCP_x_offset']}"/>
  <xacro:property name="tool_tcp_offset_y" value="${Gripper_jaw_1_dict['tool_TCP_y_offset']}"/>
  <xacro:property name="tool_tcp_offset_z" value="${Gripper_jaw_1_dict['tool_TCP_z_offset']}"/>

  <!--%%%%%%%%%%%%% The parameters here are interchangeable %%%%%%%%%%%%%-->
  <!--%%%%%%%%%%%%% Jaw 1 Definitions %%%%%%%%%%%%%-->
  <link
    name="Tool_Parallel_Gripper_Jaw_1_attachment">
    <inertial>
      <origin
        xyz="${Gripper_jaw_1_xyz}"
        rpy="${Gripper_jaw_1_rpy}"/>
      <mass
        value="${Gripper_jaw_1_mass}"/>
      <inertia
        ixx="${Gripper_jaw_1_inertia_ixx}"
        ixy="${Gripper_jaw_1_inertia_ixy}"
        ixz="${Gripper_jaw_1_inertia_ixz}"
        iyy="${Gripper_jaw_1_inertia_iyy}"
        iyz="${Gripper_jaw_1_inertia_iyz}"
        izz="${Gripper_jaw_1_inertia_izz}" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/${Gripper_jaw_1_visual_filename}" />      
      </geometry>
      <material
        name="">
        <color
          rgba="0.780392156862745 0.76078431372549 0.741176470588235 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/${Gripper_jaw_1_visual_filename}" />      
      </geometry>
    </collision>
  </link>

  <gazebo reference="Tool_Parallel_Gripper_Jaw_1_attachment">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>

  <joint
    name="Tool_Parallel_Gripper_Jaw_1_attachment_Joint"
    type="fixed">
    <origin
      xyz="0.0 0.0 0 "
      rpy="1.570796327 0 3.141592654" />
    <parent
      link="Tool_Parallel_Gripper_Jaw_1_Point" />
    <child
      link="Tool_Parallel_Gripper_Jaw_1_attachment" />
  </joint>

  <link
    name="Tool_Parallel_Gripper_Jaw_2_attachment">
    <inertial>
      <origin
        xyz="${Gripper_jaw_2_xyz}"
        rpy="${Gripper_jaw_2_rpy}"/>
      <mass
        value="${Gripper_jaw_2_mass}"/>
      <inertia
        ixx="${Gripper_jaw_2_inertia_ixx}"
        ixy="${Gripper_jaw_2_inertia_ixy}"
        ixz="${Gripper_jaw_2_inertia_ixz}"
        iyy="${Gripper_jaw_2_inertia_iyy}"
        iyz="${Gripper_jaw_2_inertia_iyz}"
        izz="${Gripper_jaw_2_inertia_izz}" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="1.570796327 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/${Gripper_jaw_2_visual_filename}" />      
      </geometry>
      <material
        name="">
        <color
          rgba="0.780392156862745 0.76078431372549 0.741176470588235 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Tools/Parallel_Gripper_1_Jaw/SmarAct_Piezo_Gripper/${Gripper_jaw_2_visual_filename}" />      
      </geometry>
    </collision>
  </link>

  <gazebo reference="Tool_Parallel_Gripper_Jaw_2_attachment">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>

  <joint
    name="Tool_Parallel_Gripper_Jaw_2_attachment_Joint"
    type="fixed">
    <origin
      xyz="0.0 0 0 "
      rpy="0 0 3.141592654" />
    <parent
      link="Tool_Parallel_Gripper_Jaw_2_Point" />
    <child
      link="Tool_Parallel_Gripper_Jaw_2_attachment" />
  </joint>


<link name="PM_Robot_Tool_TCP">
</link>

<xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_x" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['x_offset']}"/>
<xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_y" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['y_offset']}"/>
<xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_z" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['z_offset']}"/>
<xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_rx" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['rx_offset']}"/>
<xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_ry" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['ry_offset']}"/>
<xacro:property name="PM_Robot_Tool_TCP_Joint_Cal_rz" value="${calibration_dict['PM_Robot_Tool_TCP_Joint']['rz_offset']}"/>

<joint name="PM_Robot_Tool_TCP_Joint" type="fixed">
  <origin xyz="
    ${0 + tool_tcp_offset_x  + PM_Robot_Tool_TCP_Joint_Cal_x * 0.000001} 
    ${0 + tool_tcp_offset_y  + PM_Robot_Tool_TCP_Joint_Cal_y * 0.000001} 
    ${0 + tool_tcp_offset_z - 0.04542 + PM_Robot_Tool_TCP_Joint_Cal_z * 0.000001}" rpy="
    ${0 + PM_Robot_Tool_TCP_Joint_Cal_rx * 3.14159265359/180} 
    ${0 + PM_Robot_Tool_TCP_Joint_Cal_ry * 3.14159265359/180} 
    ${0 + PM_Robot_Tool_TCP_Joint_Cal_rz * 3.14159265359/180}" />
  <parent link="Gripper_Rot_Plate" />
  <child link="PM_Robot_Tool_TCP" />
  <axis xyz="0 0 0" />
</joint>
</xacro:macro>

</robot>
