controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_trajectory_controller_gripper:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster_gripper:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller_gripper:
   ros__parameters:
    joints:
      - Tool_Gripper_MPG_10_Jaw_1_Joint
      #- Tool_Gripper_MPG_10_Jaw_2_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    #open_loop_control: true
    #allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.2 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)



