controller_manager:
  ros__parameters:
    pm_parallel_gripper_2_jaws_controller:
      type: position_controllers/JointGroupPositionController
    
    pm_parallel_gripper_jaw_controller:
      type: position_controllers/JointGroupPositionController

pm_parallel_gripper_2_jaws_controller:
  ros__parameters:
    joints:
      - Tool_Parallel_Gripper_Jaw_1_Joint
      - Tool_Parallel_Gripper_Jaw_2_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position

pm_parallel_gripper_jaw_controller:
  ros__parameters:
    joints:
      - Tool_Parallel_Gripper_Jaw_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position

