controller_manager:
  ros__parameters:
    update_rate: 100

    pm_robot_gonio_right_controller:
      type: type: joint_trajectory_controller/JointTrajectoryController

    pm_robot_gonio_right_JSB:
      type: joint_state_broadcaster/JointStateBroadcaster


pm_robot_gonio_right_controller:
  ros__parameters:
    joints:
      - Gonio_Right_Stage_1_Joint
      - Gonio_Right_Stage_2_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

