controller_manager:
  ros__parameters:
    pm_parallel_gripper_2_jaws_controller:
      type: position_controllers/JointGroupPositionController
    
pm_parallel_gripper_2_jaws_controller:
  ros__parameters:
    joints:
      - Tool_Parallel_Gripper_Jaw_Joint_1
      - Tool_Parallel_Gripper_Jaw_Joint_2

    command_interfaces:
      - position

    state_interfaces:
      - position
