controller_manager:
  ros__parameters:
    update_rate: 100

    pm_robot_gonio_left_controller:
      #type: position_controllers/JointGroupPositionController
      type: joint_trajectory_controller/JointTrajectoryController

    # pm_robot_gonio_left_JSB:
    #   type: joint_state_broadcaster/JointStateBroadcaster


pm_robot_gonio_left_controller:
  ros__parameters:
    joints:
      - Gonio_Left_Stage_1_Joint
      - Gonio_Left_Stage_2_Joint

    #interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
