controller_manager:
  ros__parameters:
    update_rate: 100

    pm_robot_gonio_right_JTC:
      type: joint_trajectory_controller/JointTrajectoryController

    pm_robot_gonio_right_JSB:
      type: joint_state_broadcaster/JointStateBroadcaster


pm_robot_gonio_right_JTC:
  ros__parameters:
    joints:
      - Gonio_Right_Stage_1_Joint
      - Gonio_Right_Stage_2_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 220.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    #open_loop_control: true
    #allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.2 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

