controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # joint_trajectory_controller_Gripper:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # joint_state_broadcaster_Gripper:
    #   type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - 1K_Dispenser_Flap_Joint
      - 1K_Dispenser_Joint
      # - EQ_Joint
      # - Camera_Calibartion_Joint
      # - UV_Cart_Left_Joint
      # - UV_Module_Left_Joint
      # - UV_Cart_Right_Joint
      # - UV_Module_Right_Joint

    interface_name: position


joint_trajectory_controller:
  ros__parameters:
    joints:
      - X_Axis_Joint
      - Y_Axis_Joint
      - Z_Axis_Joint
      - Gripper_Rot_Plate_Joint


    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
    state_publish_rate: 220.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    #open_loop_control: true
    #allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.2 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
      X_Axis_Joint: { trajectory: 0.2, goal: 0.0 }
      Y_Axis_Joint: { trajectory: 0.2, goal: 0.0 }
      Z_Axis_Joint: { trajectory: 0.2, goal: 0.0 }
