controller_manager:
  ros__parameters:
    update_rate: 100

    pm_robot_forward_position_controller:
     type: position_controllers/JointGroupPositionController

    pm_robot_xyz_axis_JTC:
      type: joint_trajectory_controller/JointTrajectoryController

    pm_robot_t_axis_JTC:
      type: joint_trajectory_controller/JointTrajectoryController

    pm_robot_xyz_axis_JSB:
      type: joint_state_broadcaster/JointStateBroadcaster

    pm_robot_t_axis_JSB:
      type: joint_state_broadcaster/JointStateBroadcaster

pm_robot_forward_position_controller:
  ros__parameters:
    joints:
      - 1K_Dispenser_Flap_Joint
      #- 2K_Dispenser_Joint
      - Calibration_Qube_Joint
      #- 1K_Dispenser_Joint
      # - EQ_Joint
      # - Camera_Calibartion_Joint
      # - UV_Cart_Left_Joint
      # - UV_Module_Left_Joint
      # - UV_Cart_Right_Joint
      # - UV_Module_Right_Joint

    interface_name: position

pm_robot_t_axis_JTC:
  ros__parameters:
    joints:
      - T_Axis_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

pm_robot_xyz_axis_JTC:
  ros__parameters:
    joints:
      - X_Axis_Joint
      - Y_Axis_Joint
      - Z_Axis_Joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    # state_publish_rate: 220.0 # Defaults to 50
    # action_monitor_rate: 20.0 # Defaults to 20

    # allow_partial_joints_goal: false # Defaults to false
    # #open_loop_control: true
    # #allow_integration_in_goal_trajectories: true
    # constraints:
    #   stopped_velocity_tolerance: 0.2 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)
    #   X_Axis_Joint: { trajectory: 0.2, goal: 0.0 }
    #   Y_Axis_Joint: { trajectory: 0.2, goal: 0.0 }
    #   Z_Axis_Joint: { trajectory: 0.2, goal: 0.0 }


