pm_robot_tools:
  MPG_10:
    with_Tool_MPG_10: false
    Config:
      with_Tool_MPG_10_Jaw_3mm_Lens: false

  SPT_Tool_Holder:
    with_Tool_SPT_Holder: false
    Config:
      with_SPT_R_A1000_I500: true
  
  pm_robot_vacuum_tools:
    use_vacuum_tool: true
    use_tool: "Siemens_Vacuum_Array"
    availabe_chucks: 
      - "SPT_R_A1000_I500"
      - "Siemens_Vacuum_Array"


pm_robot_gonio_right:
  with_Gonio_Right: true
  use_chuck: "chuck_gonio_right_Siemens_UFC"
  availabe_chucks: 
    - "chuck_gonio_right_Siemens_UFC"

pm_robot_gonio_left:
  with_Gonio_Left: true
  use_chuck: "chuck_gonio_left_Siemens_Carrier"
  availabe_chucks: 
    - "chuck_gonio_left_Siemens_Carrier"


pm_robot_1K_dispenser_tip:
  use_dispenser_tip: "Dis_Tip_Yellow_I_100_A240_L12700"
  availabe_dispenser_tips: 
    - "Dis_Tip_Yellow_I_100_A240_L12700"
    - "Dis_Tip_Lavender_I_150_A310_L12700"
    - "Dis_Tip_Red_I_250_A520_L12700"

measuring_systems:
  use_keyence_bottom: false