measuring_systems:
  use_keyence_bottom: false
  use_confocal_bottom: true
  use_confocal_head: true
pm_robot_1K_dispenser_tip:
  availabe_dispenser_tips:
  - Dis_Tip_Yellow_I_100_A240_L12700
  - Dis_Tip_Lavender_I_150_A310_L12700
  - Dis_Tip_Red_I_250_A520_L12700
  use_dispenser_tip: Dis_Tip_Red_I_250_A520_L12700
pm_robot_gonio_left:
  availabe_chucks:
  - chuck_gonio_left_Siemens_Carrier
  - chuck_gonio_left_Siemens_Sensor
  - chuck_gonio_left_IPEG_Demonstrator
  use_chuck: chuck_gonio_left_Siemens_Sensor
  with_Gonio_Left: true
pm_robot_gonio_right:
  availabe_chucks:
  - chuck_gonio_right_Siemens_UFC
  - chuck_gonio_right_double_lens_holder_12_7
  - chuck_gonio_right_ipeg_active_alignment_station
  use_chuck: chuck_gonio_right_Siemens_UFC
  with_Gonio_Right: true
pm_robot_tools:
  pm_robot_tool_parallel_gripper_1_jaw:
    available_tools:
    - availabe_jaws:
      - Default_Jaw
      tool_name: SmarAct_Piezo_Gripper
    use_jaw_type: Default_Jaw
    use_paralell_gripper: false
    use_tool: SmarAct_Piezo_Gripper
  pm_robot_tool_parallel_gripper_2_jaws:
    available_tools:
    - availabe_jaws:
      - Jaw_3mm_Lens
      tool_name: Schunk_MPG_10_plus
    use_jaw_type: Jaw_3mm_Lens
    use_paralell_gripper: false
    use_tool: Schunk_MPG_10_plus
  pm_robot_vacuum_tools:
    availabe_tools:
    - availabe_tips:
      - Tip_R_A1000_I500
      tool_name: Tool_SPT_Toolholder
    - availabe_tips:
      - Tip_R_A1000_I500
      tool_name: Tool_Schunk_SPT_Tool_old
    - availabe_tips:
      - Tip_Siemens_Vacuum_Array
      tool_name: Siemens_Vacuum_Array
    - availabe_tips:
      - Tip_Lens_12_7
      tool_name: Schunk_Lens_Gripper
    - availabe_tips:
      - Tip_Lens_12_7_long
      tool_name: Schunk_Lens_Gripper_long
    use_tip: Tip_Siemens_Vacuum_Array
    use_tool: Siemens_Vacuum_Array
    use_vacuum_tool: true
pm_smparpod_station:
  with_smarpod_station: false   
  availabe_chucks:
  - test1
  - test2
  use_chuck: test1
adhesive_test_point_station:
  - num_x_points: 8
    num_y_points: 8
    grid_x_spacing: 5
    grid_y_spacing: 5
    current_point: 0
    parent_frame:
      frame_id: Test_Station
      offset_x: 4
      offset_y: 4
      offset_z: 0
      roll: 0
      pitch: 0
      yaw: 0
  - num_x_points: 8
    num_y_points: 8
    grid_x_spacing: 5
    grid_y_spacing: 5
    current_point: 0
    parent_frame:
      frame_id: Test_Station
      offset_x: 4
      offset_y: 58
      offset_z: 0
      roll: 0
      pitch: 0
      yaw: 0