pm_robot_tools:
  pm_robot_vacuum_tools:
    use_vacuum_tool: true
    use_tool: "Siemens_Vacuum_Array"
    use_tip: "Tip_Siemens_Vacuum_Array"

    availabe_tools:             #This is just a list and is not used. Its to remind the user of available configs. Make sure these names match the yamls in robot_description
      - "Tool_Schunk_SPT_Tool":
        availabe_tips:
          - "Tip_R_A1000_I500"
      - "Siemens_Vacuum_Array":
        availabe_tips:
          - "Tip_Siemens_Vacuum_Array"
      - "Schunk_Lens_Gripper":
        availabe_tips:
          - "Tip_Lens_12_7"

  pm_robot_tool_parallel_gripper_1_jaw:
    use_paralell_gripper: false
    use_tool: "SmarAct_Piezo_Gripper"
    use_jaw_type: "Default_Jaw"

    available_tools:
      - "SmarAct_Piezo_Gripper":
        availabe_jaws:
          - "Default_Jaw"

  pm_robot_tool_parallel_gripper_2_jaws:
    use_paralell_gripper: false
    use_tool: "Schunk_MPG_10_plus"
    use_jaw_type: "Jaw_3mm_Lens"

    available_tools:
      - "Schunk_MPG_10_plus":
        availabe_jaws:
          - "Jaw_3mm_Lens"
      
pm_robot_gonio_right:
  with_Gonio_Right: true
  use_chuck: "chuck_gonio_right_Siemens_UFC"
  availabe_chucks: 
    - "chuck_gonio_right_Siemens_UFC"

pm_robot_gonio_left:
  with_Gonio_Left: true
  use_chuck: "chuck_gonio_left_Siemens_Carrier"
  availabe_chucks: 
    - "chuck_gonio_left_Siemens_Carrier"

pm_robot_1K_dispenser_tip:
  use_dispenser_tip: "Dis_Tip_Yellow_I_100_A240_L12700"
  availabe_dispenser_tips: 
    - "Dis_Tip_Yellow_I_100_A240_L12700"
    - "Dis_Tip_Lavender_I_150_A310_L12700"
    - "Dis_Tip_Red_I_250_A520_L12700"

measuring_systems:
  use_keyence_bottom: false
