controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

    pm_gripper_controller:
      type: pm_smaract_gripper_controller/PMGripperController

pm_gripper_controller:
  ros__parameters: {}
