<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->

     <robot xmlns:xacro="http://ros.org/wiki/xacro">
      <xacro:macro name="pm_robot_gonio_right" params="launch_mode">
  
    <!-- Loading of the Robot Joint calibrations -->
    <xacro:if value="${launch_mode == 'sim_HW'}">
      <xacro:property name="pm_robot_joint_calibraion_file" value="$(find pm_robot_description)/calibration_config/pm_robot_joint_calibration.yaml" />
      <xacro:property name="pm_robot_bringup_config_file" value="$(find pm_robot_bringup)/config/pm_robot_bringup_config.yaml" />
    </xacro:if>
  
    <!-- If launch_mode 'real' a local path can be specified for the calibration file -->
    <xacro:if value="${launch_mode == 'real_HW'}">
      <xacro:property name="local_file_paths__file" value="$(find pm_robot_description)/calibration_config/pm_robot_path_real_HW.yaml" />
      <xacro:property name="path_dict" value="${xacro.load_yaml(local_file_paths__file)}"/>
  
      <xacro:property name="local_calibration_file_path" value="${path_dict['pm_robot_calibration_file_path']}"/>
      <xacro:property name="local_robot_bringup_file_path" value="${path_dict['pm_robot_bringup_config_file_path']}"/>
  
      <!-- REAL -->
      <!-- <xacro:property name="pm_robot_joint_calibraion_file" value="${local_calibration_file_path}" />
      <xacro:property name="pm_robot_bringup_config_file" value="${local_robot_bringup_file_path}"/> -->
  
      <!-- SIM -->
      <xacro:property name="pm_robot_joint_calibraion_file" value="$(find pm_robot_description)/calibration_config/pm_robot_joint_calibration.yaml" />
      <xacro:property name="pm_robot_bringup_config_file" value="$(find pm_robot_bringup)/config/pm_robot_bringup_config.yaml" />
  
    </xacro:if>
  

    <xacro:property name="current_pm_robot_bringup_config" value="${xacro.load_yaml(pm_robot_bringup_config_file)}"/>
    <xacro:property name="current_gonio_right_chuck" value="${current_pm_robot_bringup_config['pm_robot_gonio_right']['use_chuck']}"/>
  
    <xacro:property name="calibration_dict" value="${xacro.load_yaml(pm_robot_joint_calibraion_file)}"/>

    <!-- Init Definition of gonio chuck dict -->
    <xacro:property name="gonio_right_configs_file" value="$(find pm_robot_description)/urdf/urdf_configs/gonio_right_chuck_config.yaml" />
    <xacro:property name="gonio_right_configs_dict" value="${xacro.load_yaml(gonio_right_configs_file)}"/>

<!--%%%%%%%%%%%%% Gonio_Right Definitions %%%%%%%%-->

  <xacro:property name="gonio_offset_smarpod_x" value="0.0"/>
  <xacro:property name="gonio_offset_smarpod_y" value="0.0"/>

  <xacro:if value="${current_pm_robot_bringup_config['pm_smparpod_station']['with_smarpod_station']}">
    <xacro:property name="gonio_offset_smarpod_x" value="0.0"/>
    <xacro:property name="gonio_offset_smarpod_y" value="0.6"/>
  </xacro:if>


  <link
    name="Gonio_Base_Right">
    <inertial>
      <origin
        xyz="0.0750000000000001 0.0875 0.0967750321735945"
        rpy="0 0 0" />
      <mass
        value="0.735149712395275" />
      <inertia
        ixx="0.00216092025189497"
        ixy="-1.14771309991733E-20"
        ixz="-3.69522069861046E-19"
        iyy="0.00218184071743384"
        iyz="5.29016162077308E-20"
        izz="0.000537834506363752" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Base_Right.STL" />
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Base_Right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="Gonio_Base_Right_Joint"
    type="fixed">
    <origin
      xyz="${0.750000000000003+gonio_offset_smarpod_x} ${0.31+gonio_offset_smarpod_y} 0"
      rpy="0 0 0" />
    <parent
      link="pm_robot_base_link" />
    <child
      link="Gonio_Base_Right" />
    <axis
      xyz="0 0 0" />
  </joint>

  <!--%%%%%%%%%%%%% Gonio_Right Stage Bottom Definitions-->

  <link
    name="Gonio_Right_Stage_1_Bottom">
    <inertial>
      <origin
        xyz="0.0324999714370309 0.047395624544027 0.00802879322662528"
        rpy="0 0 0" />
      <mass
        value="0.0706349432835732" />
      <inertia
        ixx="3.36962706733941E-05"
        ixy="-7.72258832734556E-11"
        ixz="1.91981813987574E-11"
        iyy="1.80040681232712E-05"
        iyz="1.39266767162922E-07"
        izz="4.86217530226207E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Stage_1.STL" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Stage_1.STL" />
      </geometry>
    </collision>
  </link>

  <!---Gravity off-->
  <gazebo reference="Gonio_Right_Stage_1_Bottom">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>

  <joint
    name="Gonio_Right_Stage_1_Bottom_Joint"
    type="fixed">
    <origin
      xyz="0.0425000000000001 0.055 0.1847"
      rpy="0 0 0" />
    <parent
      link="Gonio_Base_Right" />
    <child
      link="Gonio_Right_Stage_1_Bottom" />
    <axis
      xyz="0 0 0" />
  </joint>


  <!--%%%%%%%%%%%%% Gonio_Right Stage 1 Top Definitions-->

  <link
    name="Gonio_Right_Stage_1_Top">
    <inertial>
      <origin
        xyz="0.0077656346142585 1.2386734954406E-07 -0.0788347959618216"
        rpy="0 0 0" />
      <mass
        value="0.135485828183631" />
      <inertia
        ixx="4.16210408086868E-05"
        ixy="8.20165428583359E-11"
        ixz="1.10769519244694E-07"
        iyy="6.29207513367838E-05"
        iyz="-3.32779841267041E-11"
        izz="9.71908514123066E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Stage_1_Upper.STL" />
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Stage_1_Upper.STL" />
      </geometry>
    </collision>
  </link>
  <!---Gravity off-->
  <gazebo reference="Gonio_Right_Stage_1_Top">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <joint
    name="Gonio_Right_Stage_1_Joint"
    type="revolute">
    <origin
      xyz="0.0325000000000002 0.0324999999999998 0.11"
      rpy="0 0 0" />
    <parent
      link="Gonio_Right_Stage_1_Bottom" />
    <child
      link="Gonio_Right_Stage_1_Top" />
    <axis
      xyz="1 0 0" />
    <limit lower="-0.087266" upper="0.087266" effort="100" velocity="0.1" />
  </joint>


  <!--%%%%%%%%%%%%% Gonio_Right Stage 2 Bottom Definitions-->

  <link
    name="Gonio_Right_Stage_2_Bottom">
    <inertial>
      <origin
        xyz="-7.70701058527834E-10 -8.11599565331278E-10 -0.0578599597513434"
        rpy="0 0 0" />
      <mass
        value="0.0546397543064688" />
      <inertia
        ixx="2.38958828661975E-05"
        ixy="-1.02198811346103E-11"
        ixz="8.61195751309108E-13"
        iyy="1.83573872586576E-05"
        iyz="-3.03498650720311E-13"
        izz="3.93608749922963E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Stage_2_Upper.STL" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Stage_2_Upper.STL" />
      </geometry>
    </collision>
  </link>

  <!---Gravity off-->
  <gazebo reference="Gonio_Right_Stage_2_Bottom">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>

  <joint
    name="Gonio_Right_Stage_2_Joint"
    type="revolute">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent
      link="Gonio_Right_Stage_1_Top" />
    <child
      link="Gonio_Right_Stage_2_Bottom" />
    <axis
      xyz="0 -1 0" />
    <limit lower="-0.17453" upper="0.17453" effort="100" velocity="0.1" />
  </joint>

  <!--%%%%%%%%%%%%% Gonio Right Chuck Definitions-->

  <link
    name="Gonio_Right_Chuck_Origin">
  </link>

  <joint
    name="Gonio_Right_Chuck_Origin_Joint"
    type="fixed">
    <origin
      xyz="0 0 -0.05"
      rpy="0 0 0" />
    <parent
      link="Gonio_Right_Stage_2_Bottom" />
    <child
      link="Gonio_Right_Chuck_Origin" />
    <axis
      xyz="0 0 0" />
  </joint>

  <!--%%%%%%%%%%%%% This is for the Chuck  -->
  <xacro:property name="gonio_chuck_tcp_offset_x_1" value="${gonio_right_configs_dict[current_gonio_right_chuck]['spawn_1_offset_from_gonio_x']}"/>
  <xacro:property name="gonio_chuck_tcp_offset_y_1" value="${gonio_right_configs_dict[current_gonio_right_chuck]['spawn_1_offset_from_gonio_y']}"/>
  <xacro:property name="gonio_chuck_tcp_offset_z_1" value="${gonio_right_configs_dict[current_gonio_right_chuck]['spawn_1_offset_from_gonio_z']}"/>
  <xacro:property name="gonio_chuck_tcp_offset_x_2" value="${gonio_right_configs_dict[current_gonio_right_chuck]['spawn_2_offset_from_gonio_x']}"/>
  <xacro:property name="gonio_chuck_tcp_offset_y_2" value="${gonio_right_configs_dict[current_gonio_right_chuck]['spawn_2_offset_from_gonio_y']}"/>
  <xacro:property name="gonio_chuck_tcp_offset_z_2" value="${gonio_right_configs_dict[current_gonio_right_chuck]['spawn_2_offset_from_gonio_z']}"/>
  
  <xacro:property name="gonio_chuck_xyz" value="${gonio_right_configs_dict[current_gonio_right_chuck]['xyz']}"/>
  <xacro:property name="gonio_chuck_xyz" value="${gonio_right_configs_dict[current_gonio_right_chuck]['xyz']}"/>
  <xacro:property name="gonio_chuck_xyz" value="${gonio_right_configs_dict[current_gonio_right_chuck]['xyz']}"/>
  <xacro:property name="gonio_chuck_rpy" value="${gonio_right_configs_dict[current_gonio_right_chuck]['rpy']}"/>
  <xacro:property name="gonio_chuck_mass" value="${gonio_right_configs_dict[current_gonio_right_chuck]['mass']}"/>
  <xacro:property name="gonio_chuck_inertia_ixx" value="${gonio_right_configs_dict[current_gonio_right_chuck]['inertia_ixx']}"/>
  <xacro:property name="gonio_chuck_inertia_ixy" value="${gonio_right_configs_dict[current_gonio_right_chuck]['inertia_ixy']}"/>
  <xacro:property name="gonio_chuck_inertia_ixz" value="${gonio_right_configs_dict[current_gonio_right_chuck]['inertia_ixz']}"/>
  <xacro:property name="gonio_chuck_inertia_iyy" value="${gonio_right_configs_dict[current_gonio_right_chuck]['inertia_iyy']}"/>
  <xacro:property name="gonio_chuck_inertia_iyz" value="${gonio_right_configs_dict[current_gonio_right_chuck]['inertia_iyz']}"/>
  <xacro:property name="gonio_chuck_inertia_izz" value="${gonio_right_configs_dict[current_gonio_right_chuck]['inertia_izz']}"/>
  <xacro:property name="gonio_chuck_color" value="${gonio_right_configs_dict[current_gonio_right_chuck]['color']}"/>    
  <xacro:property name="gonio_chuck_visual_filename" value="${gonio_right_configs_dict[current_gonio_right_chuck]['visual_filename']}"/>
  <xacro:property name="gonio_chuck_collision_filename" value="${gonio_right_configs_dict[current_gonio_right_chuck]['collision_filename']}"/>

<link
  name="Gonio_Right_Chuck">
  <inertial>
    <origin
      xyz="${gonio_chuck_xyz}"
      rpy="${gonio_chuck_rpy}"/>
    <mass
      value="${gonio_chuck_mass}"/>
    <inertia
      ixx="${gonio_chuck_inertia_ixx}"
      ixy="${gonio_chuck_inertia_ixy}"
      ixz="${gonio_chuck_inertia_ixz}"
      iyy="${gonio_chuck_inertia_iyy}"
      iyz="${gonio_chuck_inertia_iyz}"
      izz="${gonio_chuck_inertia_izz}" />
  </inertial>
  <visual>
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <geometry>
      <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Chucks/${gonio_chuck_visual_filename}" />      
    </geometry>
    <material
      name="${gonio_chuck_color}">
    </material>
  </visual>
  <collision>
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <geometry>
      <mesh filename="file://$(find pm_robot_description)/meshes/Gonio_Right/Gonio_Right_Chucks/${gonio_chuck_collision_filename}" />         
    </geometry>
  </collision>
</link>

<joint
  name="Gonio_Right_Chuck_Joint"
  type="fixed">
  <origin
    xyz="0 0 0"
    rpy="0 0 0" />
  <parent
    link="Gonio_Right_Chuck_Origin" />
  <child
    link="Gonio_Right_Chuck" />
  <axis
    xyz="0 0 0" />
</joint>
  
  <!--%%%%%%%%%%%%% Gonio Right Part 1 Origin -->
  <link
    name="Gonio_Right_Part_1_Origin">
  </link>

  <joint
    name="Gonio_Right_Part_1_Origin_Joint"
    type="fixed">
    <origin
      xyz="${gonio_chuck_tcp_offset_x_1} ${gonio_chuck_tcp_offset_y_1} ${gonio_chuck_tcp_offset_z_1}"
      rpy="0 0 0" />
    <parent
      link="Gonio_Right_Chuck_Origin" />
    <child
      link="Gonio_Right_Part_1_Origin" />
    <axis
      xyz="0 0 0" />
  </joint>

  <!--%%%%%%%%%%%%% Gonio Right Part 2 Origin -->
  <link
    name="Gonio_Right_Part_2_Origin">
  </link>

  <joint
    name="Gonio_Right_Part_2_Origin_Joint"
    type="fixed">
    <origin
      xyz="${gonio_chuck_tcp_offset_x_2} ${gonio_chuck_tcp_offset_y_2} ${gonio_chuck_tcp_offset_z_2}"
      rpy="0 0 0" />
    <parent
      link="Gonio_Right_Chuck_Origin" />
    <child
      link="Gonio_Right_Part_2_Origin" />
    <axis
      xyz="0 0 0" />
  </joint>

</xacro:macro>

</robot>